import '../globals.css'
import Head from "next/head"
import SiteLayout from '@components/SiteLayout'

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>frontseat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteLayout>
        <Component {...pageProps} />
      </SiteLayout>
    </div>
  )
}

export default MyApp
